version: '3.8'

services:
  postgres:
    image: postgres:17.3
    container_name: postgres
    environment:
      POSTGRES_USER: alik
      POSTGRES_PASSWORD: alik
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-scripts/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      - team_cloud_net
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:9.0
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: alik@crazy.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - team_cloud_net
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak_db
      KC_DB_SCHEMA: keycloak_schema
      KC_DB_USERNAME: alik
      KC_DB_PASSWORD: alik
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080

      KC_LOG_LEVEL: info
      KC_HEALTH_ENABLED: true

      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    depends_on:
      - postgres
    ports:
      - "9090:8080"
    networks:
      - team_cloud_net
    command: start-dev --import-realm
    restart: unless-stopped

  minio:
    container_name: minio
    image: quay.io/minio/minio:latest
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "adminpassword78"
    volumes:
      - minio_data:/data
    depends_on:
      - postgres
    ports:
      - "9000:9000"
      - "9091:9091"
    networks:
      - team_cloud_net
    restart: unless-stopped
    command: server --console-address ":9091" /data


networks:
  team_cloud_net:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
  minio_data: