version: '3.8'

services:
  postgres:
    image: postgres:17.3
    container_name: postgres_db
    environment:
      POSTGRES_USER: alik
      POSTGRES_PASSWORD: alik
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - team_cloud_net
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:9.0
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: alik@crazy.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - team_cloud_net
    restart: unless-stopped


networks:
  team_cloud_net:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data: