server:
  port: 8081
spring:
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/team_db?currentSchema=team_schema
      username: alik
      password: alik
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true
    default-schema: team_schema
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/team_cloud
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:9090/realms/team_cloud
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            client-id: team_service
            client-secret: AVrkD1vu6H8ketEfXpKOvPEiOoB36piS
            scope:
              - view_users
logging:
  level:
    org.springframework.orm.jpa: TRACE
    org.springframework.transaction.interceptor: TRACE
    com.alikgizatulin.commonlibrary: DEBUG
    com.alikgizatulin.teamapp: DEBUG