server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/team_cloud


keycloak:
  url: http://localhost:9090
  realm: team_cloud
  id: user-manager
  secret: lxvWH0hFhQSGVF9BdUqVsPkDJgFw3UlQ