server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/TeamCloud


keycloak:
  url: http://localhost:9090
  realm: TeamCloud
  id: user-manager
  secret: BwccfQ8F2L0ZvQ4J5bdsmzCv7PDcLx1j