server:
  port: 8082
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/storage_db?currentSchema=storage_schema
    username: alik
    password: alik
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true
    default-schema: storage_schema
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/team_cloud
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:9090/realms/team_cloud
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            client-id: storage_service
            client-secret: MHFVRNHSEvmV9dXhovylsH8cUuqivi0y
            scope:
              - view_teams
              - view_team_members
  servlet:
    multipart:
      max-request-size: 1GB
      max-file-size: 1GB

minio:
  endpoint: http://localhost:9000
  access_key: admin
  secret_key: adminpassword78

logging:
  level:
    org.springframework.orm.jpa: TRACE
    org.springframework.transaction.interceptor: TRACE
    com.alikgizatulin.commonlibrary: DEBUG
    com.alikgizatulin.storageapp: DEBUG